# Generated by Django 4.2.1 on 2023-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('avg_year_temp', models.IntegerField()),
                ('is_beach', models.BooleanField()),
                ('are_mountains', models.BooleanField()),
                ('top_attractions', models.CharField(max_length=500)),
                ('hotel_price', models.IntegerField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, default='')),
                ('continent', models.ManyToManyField(to='destinations.continent')),
            ],
        ),
    ]
